FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --only=production

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src/swagger ./dist/swagger
COPY --from=builder /app/src/db ./dist/db

# Create uploads, processed, and data folders
RUN mkdir -p uploads processed data

EXPOSE 5000
CMD ["node", "dist/index.js"]
